import { expect, test } from '@playwright/test'
import { ANA, CENTRO, CUBA, EVENT, installBackend, LUIS, MANIZALES, MINISTRY, PEREIRA, TERMS } from './backend'
import { expectChrome, expectClearOfNav, expectNoOverflow, expectPrimaryWidth, scrollToEnd } from './support'

test('la sesión anónima entra por Google', async ({ page }) => {
  await installBackend(page, 'anonymous')
  await page.goto('/')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('heading', { name: 'Efata' })).toBeVisible()
  await expect(page.getByText('Comunidades en Cristo')).toBeVisible()
  await expect(page.locator('main img.cf-mark')).toHaveAttribute('src', '/icons/mark.png')
  await expect(page.getByRole('link', { name: 'Continuar con Google' })).toHaveAttribute('href', '/user/login/google')
  await expect(page.getByRole('link', { name: 'usuario y contraseña' })).toHaveAttribute('href', '/user/login')
  await expect(page.getByRole('navigation', { name: 'Secciones' })).toHaveCount(0)
  await expectNoOverflow(page)
  await expectPrimaryWidth(page, page.getByRole('link', { name: 'Continuar con Google' }))
})

test('un miembro registra, corrige y deja una nota', async ({ page }) => {
  await installBackend(page, 'member')
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1, name: 'Natalia' })).toBeVisible()
  await expect(page.getByText('Falta tu nombre o tu celular en el perfil.')).toBeVisible()
  const ministryCard = page.getByRole('link', { name: /Gozo en el cielo/ })
  await expect(ministryCard).toContainText('Un espacio para compartir.')
  await expect(ministryCard.locator('svg')).toBeVisible()
  await expect(ministryCard).toHaveAttribute('href', `/comunidades/${MINISTRY}`)
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Personas que registraste' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Evangelización en Chipre/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Ver todos' })).toHaveCount(0)

  const sections = page.getByRole('navigation', { name: 'Secciones' })
  await expect(sections.getByRole('link')).toHaveCount(3)
  await ministryCard.click()
  await page.getByRole('link', { name: 'Evangelismo' }).click()
  await page.getByRole('link', { name: 'Ver el registro' }).click()
  await expect(page.getByRole('heading', { name: 'Mis evangelizados' })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toContainText('3001234567')
  await page.getByRole('link', { name: /Ana Ruiz/ }).click()

  await expect(page.getByRole('link', { name: 'Escribir por WhatsApp' })).toHaveAttribute('href', 'https://wa.me/3001234567')
  await expect(page.getByText('3001234567', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Volver' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Borrar esta ficha' })).toHaveCount(0)
  await expect(page.getByText('Volvió a la iglesia')).toBeVisible()
  await expect(page.getByText('Salud de su madre')).toBeVisible()

  await page.getByRole('link', { name: 'Corregir datos' }).click()
  await expect(page.getByLabel('Celular')).toHaveValue('3001234567')
  await expect(page.getByRole('radio', { name: 'Adulto', exact: true })).toBeChecked()
  await expect(page.getByLabel('Ciudad')).toHaveValue(MANIZALES)
  await expect(page.getByLabel('Sector donde vive')).toHaveValue(CENTRO)
  await page.getByLabel('Celular').fill('3009998877')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('link', { name: 'Escribir por WhatsApp' })).toHaveAttribute('href', 'https://wa.me/3009998877')
  await expect(page.getByText('3009998877', { exact: true })).toBeVisible()
  await expect(page.getByText('Manizales')).toBeVisible()
  await expect(page.getByText('Centro')).toBeVisible()

  await expect(page.getByRole('heading', { name: 'Notas' })).toBeVisible()
  await expect(page.getByLabel('Nueva nota')).toHaveCount(0)
  await page.getByRole('button', { name: 'Agregar nota' }).click()
  await page.getByLabel('Nueva nota').fill('Llamar el sábado')
  await page.getByRole('button', { name: 'Guardar nota' }).click()
  await expect(page.getByText('Llamar el sábado')).toBeVisible()
  await expect(page.getByLabel('Nueva nota')).toHaveCount(0)

  await page.goto(`/evangelismo/${LUIS}`)
  await expect(page.getByText('No tienes permiso para hacer esto.')).toBeVisible()

  await page.goto('/evangelismo/nuevo')
  const savePerson = page.getByRole('button', { name: 'Guardar', exact: true })
  await savePerson.click()
  await expect(page.getByText('Elige la etapa de vida.')).toBeVisible()
  await page.getByRole('radio', { name: 'Adulto', exact: true }).check()
  await page.getByLabel('Nombre completo').fill('Pedro Luna')
  await page.getByLabel('Celular').fill('3015556677')
  await expect(page.getByLabel('Ciudad')).toHaveCount(0)
  await page.getByRole('button', { name: 'Agregar más datos' }).click()
  const sector = page.getByLabel('Sector donde vive')
  await expect(sector).toBeDisabled()
  await page.getByLabel('Ciudad').selectOption({ label: 'Manizales' })
  await expect(sector.locator('option', { hasText: 'Chipre' })).toHaveCount(1)
  await expect(sector.locator('option', { hasText: 'Cuba' })).toHaveCount(0)
  await page.getByLabel('Ciudad').selectOption({ label: 'Pereira' })
  await expect(sector.locator('option', { hasText: 'Chipre' })).toHaveCount(0)
  await expect(sector.locator('option', { hasText: 'Cuba' })).toHaveCount(1)
  await sector.selectOption({ label: 'Cuba' })
  await page.getByLabel('Petición de oración').fill('Por su familia')
  await page.getByLabel('Observaciones').fill('En la esquina del parque.')
  await expect(page.getByLabel('Evento')).toHaveValue(EVENT)
  await savePerson.click()
  await expect(page.getByText('Quedó el registro de Pedro Luna.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Registrar a otra persona' })).toBeVisible()
  await expect(page.getByLabel('Nombre completo')).toHaveValue('')
  await expect(page.getByLabel('Celular')).toHaveValue('')
  await expect(page.getByLabel('Petición de oración')).toHaveValue('')
  await expect(page.getByLabel('Observaciones')).toHaveValue('')
  await expect(page.getByRole('radio', { name: 'Adulto', exact: true })).toBeChecked()
  await expect(page.getByLabel('Ciudad')).toHaveValue(PEREIRA)
  await expect(page.getByLabel('Sector donde vive')).toHaveValue(CUBA)
  await page.getByRole('link', { name: 'Ver la ficha' }).click()
  await expect(page.getByRole('heading', { name: 'Pedro Luna' })).toBeVisible()
  await expect(page.getByText('Pereira')).toBeVisible()
  await expect(page.getByText('Cuba')).toBeVisible()
  await expect(page.getByText('Por su familia')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Evangelización en Chipre' })).toBeVisible()

  await page.goto('/evangelismo')
  const search = page.getByLabel('Buscar por nombre o celular')
  await search.fill('Pedro')
  await expect(page.getByRole('link', { name: /Pedro Luna/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toHaveCount(0)
  await search.fill('3009998877')
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Pedro Luna/ })).toHaveCount(0)
  await search.fill('zzzz')
  await expect(page.getByText('No hay personas con ese nombre.')).toBeVisible()
  await search.fill('')
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Pedro Luna/ })).toBeVisible()
  await page.getByRole('link', { name: 'Eventos' }).click()
  await expect(page.getByRole('heading', { name: 'Eventos' })).toBeVisible()
  const outing = page.getByRole('link', { name: /Evangelización en Chipre/ })
  await expect(outing).toContainText('Gozo en el cielo')
  await expect(outing).toContainText('1 registro tuyo')
  await outing.click()
  await expect(page.getByRole('heading', { name: 'Evangelización en Chipre' })).toBeVisible()
  await expect(page.getByText('1 registro tuyo')).toBeVisible()
  await expect(page.getByText('Registros abiertos')).toBeVisible()
  await expect(page.getByRole('link', { name: /Pedro Luna/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cerrar registros' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toHaveAttribute('href', `/evangelismo/nuevo?evento=${EVENT}`)

  await page.goto(`/comunidades/${MINISTRY}/eventos/nuevo`)
  await expect(page.getByText('Solo quien administra la comunidad puede registrar un evento.')).toBeVisible()
  await expect(page.getByLabel('Título')).toHaveCount(0)

  await page.goto('/evangelismo/todos')
  await expect(page.getByText('Estas son solo las personas que registraste.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Descargar CSV' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Pedro Luna/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toHaveCount(0)

  await sections.getByRole('link', { name: 'Inicio' }).click()
  await page.getByRole('link', { name: 'Gozo en el cielo' }).click()
  await expect(page.getByRole('heading', { name: 'Gozo en el cielo' })).toBeVisible()
  await expect(page.locator('.cf-ministry svg')).toBeVisible()
  await expect(page.getByText('Un espacio para compartir.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Evangelismo' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Publicaciones' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Eventos' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Miembros' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toHaveCount(0)
  await expect(page.getByText('Evangelismo activo')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Registrar evento' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Desactivar evangelismo' })).toHaveCount(0)
  await expect(page.getByText('Natalia')).toHaveCount(0)

  await page.getByRole('link', { name: 'Evangelismo' }).click()
  await expect(page.getByRole('heading', { name: 'Evangelismo' })).toBeVisible()
  await expect(page.getByText('Evangelismo activo')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Personas que registraste' })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await page.getByRole('link', { name: 'Volver' }).click()

  await page.getByRole('link', { name: 'Eventos' }).click()
  await expect(page.getByRole('heading', { name: 'Eventos' })).toBeVisible()
  await expect(page.getByRole('link', { name: /Evangelización en Chipre/ })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Registrar evento' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Volver' }).click()

  await page.getByRole('link', { name: 'Miembros' }).click()
  await expect(page.getByRole('heading', { name: 'Miembros' })).toBeVisible()
  await expect(page.getByText('Natalia')).toBeVisible()
  await page.getByRole('link', { name: 'Volver' }).click()

  await page.getByRole('link', { name: 'Publicaciones' }).click()
  await expect(page.getByText('Esta comunidad no tiene publicaciones.')).toBeVisible()

  await sections.getByRole('link', { name: 'Avisos' }).click()
  await page.getByRole('link', { name: /Evangelización en Chipre/ }).click()
  await expect(page).toHaveURL(new RegExp(`/avisos/eventos/${EVENT}$`))
  await expect(page.getByText(/27 de julio/)).toBeVisible()
  await expect(page.getByText('Nos vemos en el parque.')).toBeVisible()
  await sections.getByRole('link', { name: 'Avisos' }).click()
  await expect(page.getByRole('heading', { name: 'Artículos' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Términos de servicio' }).click()
  await expect(page).toHaveURL(new RegExp(`/avisos/paginas/${TERMS}$`))
  await expect(page.getByText('El uso del registro.')).toBeVisible()

  await sections.getByRole('link', { name: 'Perfil' }).click()
  await expect(page.getByText('natalia@example.com')).toBeVisible()
  await expect(page.getByText('Falta tu nombre o tu celular.')).toBeVisible()
  await page.getByLabel('Nombres').fill('Ana María')
  await page.getByLabel('Apellidos').fill('López')
  await page.getByLabel('Celular').fill('3001112233')
  await page.getByLabel('Fecha de nacimiento').fill('1990-04-12')
  await page.getByRole('button', { name: 'Guardar perfil' }).click()
  await expect(page.getByText('Perfil guardado.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Nombres')).toHaveValue('Ana María')
  await expect(page.getByLabel('Fecha de nacimiento')).toHaveValue('1990-04-12')
  await expect(page.getByText('Falta tu nombre o tu celular.')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Salir' })).toHaveAttribute('href', '/user/logout')

  await sections.getByRole('link', { name: 'Inicio' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Ana María' })).toBeVisible()
})

test('un líder filtra el listado completo y borra', async ({ page }) => {
  await installBackend(page, 'leader')
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Ver todos' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Gozo en el cielo' }).click()
  await page.getByRole('link', { name: 'Evangelismo' }).click()
  await page.getByRole('link', { name: 'Ver todos' }).click()
  await expect(page.getByRole('heading', { name: 'Evangelizados' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Descargar CSV' })).toHaveAttribute('href', '/admin/evangelismo/export/full')
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toBeVisible()
  const leaderSearch = page.getByLabel('Buscar por nombre o celular')
  await leaderSearch.fill('3001234567')
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toHaveCount(0)
  await leaderSearch.fill('')
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toBeVisible()

  await page.getByLabel('Etapa de vida').selectOption({ label: 'Joven' })
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toHaveCount(0)
  await page.getByLabel('Etapa de vida').selectOption({ label: 'Todas' })

  await expect(page.getByLabel('Sector')).toBeDisabled()
  await page.getByLabel('Ciudad').selectOption({ label: 'Pereira' })
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toHaveCount(0)
  await expect(page.getByLabel('Sector')).toBeEnabled()
  await page.getByLabel('Ciudad').selectOption({ label: 'Todas' })
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toBeVisible()

  await page.getByRole('link', { name: /Luis Gómez/ }).click()
  await expect(page.getByText('Registró Carmen Díaz')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Borrar esta ficha' }).click()
  await expect(page.getByRole('heading', { name: 'Mis evangelizados' })).toBeVisible()

  await page.goto('/evangelismo/todos')
  await expect(page.getByRole('link', { name: /Luis Gómez/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Ana Ruiz/ })).toBeVisible()
  await page.goto(`/evangelismo/${ANA}`)
  await expect(page.getByRole('link', { name: 'Corregir datos' })).toBeVisible()

  await page.goto('/evangelismo')
  await page.getByRole('link', { name: 'Eventos' }).click()
  await expect(page.getByRole('link', { name: 'Programar evento' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Evangelización en Chipre/ })).toContainText('0 registros')

  await page.goto(`/comunidades/${MINISTRY}/evangelismo`)
  await expect(page.getByText('Evangelismo activo')).toBeVisible()
  await page.goto(`/comunidades/${MINISTRY}/eventos`)
  await page.getByRole('link', { name: 'Registrar evento' }).click()
  await expect(page.getByRole('heading', { name: 'Registrar evento' })).toBeVisible()
  await page.getByLabel('Título').fill('Reunión general')
  await page.getByLabel('Cuándo').fill('2026-10-12T09:00')
  await page.getByRole('button', { name: 'Publicar' }).click()
  await expect(page.getByRole('heading', { name: 'Reunión general' })).toBeVisible()
  await expect(page.getByText('Evento informativo')).toBeVisible()
  await expect(page.getByText('No abre registros de evangelizados.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Registros' })).toHaveCount(0)
  await page.goto('/evangelismo/eventos')
  await expect(page.getByRole('link', { name: /Reunión general/ })).toHaveCount(0)

  await page.goto(`/comunidades/${MINISTRY}/eventos/nuevo`)
  await page.getByRole('checkbox', { name: 'Actividad de evangelismo' }).check()
  await expectNoOverflow(page)
  const openRegistrations = page.getByRole('button', { name: 'Abrir registros' })
  await expectPrimaryWidth(page, openRegistrations)
  await scrollToEnd(page)
  await expectClearOfNav(page, openRegistrations)
  await page.getByLabel('Título').fill('Salida al parque')
  await page.getByLabel('Cuándo').fill('2026-10-10T16:00')
  await openRegistrations.click()
  await expect(page.getByRole('heading', { name: 'Salida al parque' })).toBeVisible()
  await expect(page.getByText(/10 de octubre/)).toBeVisible()
  await expect(page.getByText('Registros abiertos')).toBeVisible()
  await expect(page.getByText('0 registros', { exact: true })).toBeVisible()
  await expect(page.getByText('Todavía no hay registros en este evento.')).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar registros' }).click()
  await expect(page.getByText('Registros cerrados')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Abrir registros' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toHaveCount(0)
  await page.goto('/evangelismo/eventos')
  await expect(page.getByRole('link', { name: /Salida al parque/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Reunión general/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Evangelización en Chipre/ })).toBeVisible()
})

test('la aplicación se puede instalar en el celular', async ({ page }) => {
  const manifest = await page.request.get('/manifest.webmanifest')
  expect(manifest.ok()).toBeTruthy()
  const body = await manifest.json()
  expect(body.name).toBe('Efata')
  expect(body.short_name).toBe('Efata')
  expect(body.description).toBe('Comunidades en Cristo')
  expect(body.display).toBe('standalone')
  expect(body.start_url).toBe('/')
  expect(body.icons.length).toBeGreaterThan(0)
  for (const icon of body.icons) {
    const file = await page.request.get(icon.src)
    expect(file.ok()).toBeTruthy()
    expect(file.headers()['content-type'] ?? '').toContain('image/png')
  }
  const worker = await page.request.get('/sw.js')
  expect(worker.ok()).toBeTruthy()
  expect(await worker.text()).toContain("addEventListener('fetch'")

  await installBackend(page, 'member')
  await page.goto('/perfil')
  await expect(page.getByRole('heading', { name: 'En tu celular' })).toBeVisible()
  await expect(page.getByText('En el menú del navegador, elige Instalar aplicación o Agregar a inicio.')).toBeVisible()
  await page.evaluate(() => {
    const event = new Event('beforeinstallprompt', { cancelable: true }) as Event & {
      prompt: () => Promise<void>
      userChoice: Promise<{ outcome: 'accepted' }>
    }
    event.prompt = () => Promise.resolve()
    event.userChoice = Promise.resolve({ outcome: 'accepted' })
    window.dispatchEvent(event)
  })
  await page.getByRole('button', { name: 'Instalar en el celular' }).click()
  await expect(page.getByRole('heading', { name: 'En tu celular' })).toHaveCount(0)
})

test('quien no pertenece a una comunidad ve el vacío', async ({ page }) => {
  await installBackend(page, 'outsider')
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1, name: 'Marta' })).toBeVisible()
  await expect(page.getByText('No perteneces a una comunidad todavía.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Registrar a alguien' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Personas que registraste' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Gozo en el cielo' })).toHaveCount(0)

  await page.goto('/comunidades')
  await expect(page.getByText('No perteneces a una comunidad todavía.')).toBeVisible()
  await page.goto(`/comunidades/${MINISTRY}`)
  await expect(page.getByText('No se encontró esta comunidad, o no perteneces a ella.')).toBeVisible()
})

test('la navegación y el botón primario caben en la pantalla', async ({ page }) => {
  await installBackend(page, 'member')
  const routes = [
    '/',
    '/evangelismo',
    '/evangelismo/nuevo',
    `/evangelismo/${ANA}`,
    '/evangelismo/todos',
    '/evangelismo/eventos',
    `/comunidades/${MINISTRY}/eventos/nuevo`,
    `/evangelismo/eventos/${EVENT}`,
    '/comunidades',
    `/comunidades/${MINISTRY}`,
    `/comunidades/${MINISTRY}/evangelismo`,
    `/comunidades/${MINISTRY}/publicaciones`,
    `/comunidades/${MINISTRY}/eventos`,
    `/comunidades/${MINISTRY}/miembros`,
    '/avisos',
    `/avisos/eventos/${EVENT}`,
    `/avisos/paginas/${TERMS}`,
    '/perfil',
  ]

  for (const route of routes) {
    await page.goto(route)
    await expect(page.locator('main')).toBeVisible()
    await expectChrome(page)
    await expectNoOverflow(page)
  }

  await page.goto(`/comunidades/${MINISTRY}/evangelismo`)
  await expectPrimaryWidth(page, page.getByRole('link', { name: 'Registrar a alguien' }))

  await page.goto('/evangelismo/nuevo')
  const save = page.getByRole('button', { name: 'Guardar', exact: true })
  await page.getByRole('button', { name: 'Agregar más datos' }).click()
  await expect(save).toBeVisible()
  await expectPrimaryWidth(page, save)
  await scrollToEnd(page)
  await expectClearOfNav(page, save)
  await page.getByLabel('Observaciones').evaluate((element) => {
    element.focus()
  })
  await expectClearOfNav(page, page.getByLabel('Observaciones'))

  await page.goto('/perfil')
  const saveProfile = page.getByRole('button', { name: 'Guardar perfil' })
  await expectPrimaryWidth(page, saveProfile)
  await scrollToEnd(page)
  await expectClearOfNav(page, saveProfile)
  await expectClearOfNav(page, page.getByRole('link', { name: 'Salir' }))

  await page.goto(`/evangelismo/${ANA}`)
  await expect(page.getByText('Volvió a la iglesia')).toBeVisible()
  await scrollToEnd(page)
  await expectClearOfNav(page, page.getByRole('button', { name: 'Agregar nota' }))

  const sections = page.getByRole('navigation', { name: 'Secciones' })
  await sections.getByRole('link', { name: 'Avisos' }).click()
  await expect(sections.getByRole('link', { name: 'Avisos' })).toHaveAttribute('aria-current', 'page')
  await sections.getByRole('link', { name: 'Inicio' }).click()
  await expect(sections.getByRole('link', { name: 'Inicio' })).toHaveAttribute('aria-current', 'page')
  await expect(sections.getByRole('link', { name: 'Avisos' })).not.toHaveAttribute('aria-current', 'page')
  const viewport = page.viewportSize()
  if (viewport && viewport.width >= 900) {
    await expect(sections.getByRole('paragraph')).toContainText('EFATA')
    await expect(sections.getByRole('paragraph')).toContainText('Comunidades en Cristo')
    await expect(sections.locator('img.cf-mark')).toBeVisible()
  }
})
